### PR TITLE
Caddy Config Example Fix

### PR DESCRIPTION
**Pull request by TechnicJelle**
By a user on our Discord

### CODE REVIEW

**Comment by TechnicJelle** [comment]
@Roan-V seeing as you've contributed the original Caddy example, could you please review this?

**Comment by Roan-V** [comment]
The addition of a wildcard matcher token is not necessary on the latest Caddy versions
It was needed on pre 2.8.0 versions: https://caddyserver.com/docs/caddyfile/directives/root#syntax

Can't hurt to have it added for compatibility reasons though.

lgtm!

**Comment by TechnicJelle** [comment]
Thanks!

**Comment by Roan-V** [comment]
Unsure what the point of the reverse proxy part is though.

The files are already being served through Caddy, why also reverse proxy for a seperate server/live

**Comment by TechnicJelle** [comment]
> If you are using a plugin/mod you usually have live-updating player-markers on your map. For those to work with an external web-server you will also need to reverse-proxy all requests to `/maps/*/live/*` to the builtin web-server.

**Comment by Roan-V** [comment]
Ah, yup fair in that case
My maps are all just as examples without players :P

**Comment by TechnicJelle** [comment]
Yeah, makes sense.

**Pull request merged**
